# Lesson 3: pandas

**Week 3 · Data Engineering Course**

---

pandas is the most widely used Python library for working with tabular data. It lets you load a CSV into a **DataFrame** — a table with named columns — and then filter, clean, and summarise it with just a few lines of code.

**Install before starting** (run once in your terminal):
```
pip install pandas
```

**What you will learn:**
- Loading a CSV into a DataFrame
- Exploring: shape, types, missing values, unique values, statistics
- Selecting columns and filtering rows
- Cleaning: whitespace, casing, typos, currency symbols, missing values, duplicates
- Grouping and summarising
- Writing the clean result to a new CSV

In [4]:
import pandas as pd
from pathlib import Path

RAW   = Path('../data/raw')
CLEAN = Path('../data/clean')
CLEAN.mkdir(parents=True, exist_ok=True)

print(f'pandas version: {pd.__version__}')

pandas version: 3.0.3

---

## 3.1 Loading a CSV

`pd.read_csv()` reads a CSV file into a DataFrame.

In [5]:
import pandas as pd
from pathlib import Path
raw = Path('data/raw')
df = pd.read_csv(raw / 'sales_q1.csv')

print(f'Shape {df.shape}')         # (rows, columns)
print(f'Columns: {list(df.columns)}')

Shape (26, 10)
Columns: ['order_id', 'date', 'customer_name', 'product', 'category', 'quantity', 'unit_price', 'total', 'region', 'sales_rep']

---

## 3.2 Exploring the Data

Before cleaning anything, look at the data. These steps take under a minute and tell you almost everything you need.

In [6]:
df.head()    # first 5 rows

,order_id,date,customer_name,product,category,quantity,unit_price,total,region,sales_rep
0,1001,2023-01-05,Alice Johnson,Laptop,Electronics,1,1200.00,1200.0,North,James Carter
1,1002,2023-01-08,Bob Smith,Cotton T-Shirt,Clothing,3,25.00,75.0,East,David Chen
2,1003,2023-01-12,Carol Williams,Gaming Mouse,ELECTRONICS,2,35.00,70.0,West,Sarah Williams
3,1004,15/01/2023,David Brown,Coffee Maker,Home & Kitchen,1,80.00,80.0,South,Maria Lopez
4,1005,2023-01-18,Emma Jones,Laptop,Electronics,1,1200.00,NaN,North,James Carter

In [7]:
df.tail(3)   # last 3 rows — useful for checking that the file did not get cut off

,order_id,date,customer_name,product,category,quantity,unit_price,total,region,sales_rep
23,1023,2023-03-28,Carol Williams,Standing Desk,HOME & KITCHEN,1,350.00,350.0,West,Sarah Williams
24,1024,2023-03-30,David Brown,Cotton T-Shirt,Clothing,5,25.00,125.0,NaN,NaN
25,1025,2023-03-31,Emma Jones,Running Sneakers,Clothing,1,90.00,90.0,North,James Carter

In [8]:
df.info()    # column names, non-null counts, data types

<class 'pandas.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       26 non-null     int64
 1   date           26 non-null     str
 2   customer_name  26 non-null     str
 3   product        26 non-null     str
 4   category       26 non-null     str
 5   quantity       26 non-null     int64
 6   unit_price     26 non-null     str
 7   total          24 non-null     float64
 8   region         24 non-null     str
 9   sales_rep      25 non-null     str
dtypes: float64(1), int64(2), str(7)
memory usage: 2.2 KB

In [9]:
# df.describe() gives statistics for every numeric column
# count, mean, min, max, and percentiles
df.describe()

          order_id   quantity        total
count    26.000000  26.000000    24.000000
mean   1012.615385   1.576923   235.416667
std       7.473028   1.270372   314.621638
min    1001.000000  -2.000000   -90.000000
25%    1006.250000   1.000000    78.750000
50%    1012.500000   1.000000   132.500000
75%    1018.750000   2.000000   250.000000
max    1025.000000   5.000000  1200.000000

In [10]:
# Missing values per column
print(df.isnull().sum())

order_id         0
date             0
customer_name    0
product          0
category         0
quantity         0
unit_price       0
total            2
region           2
sales_rep        1
dtype: int64

In [11]:
# Unique values in the category column — quickly reveals casing problems and typos
print(df['category'].value_counts())
print(f'\nUnique categories: {df["category"].nunique()}')

category
Clothing          6
Electronics       5
Home & Kitchen    5
ELECTRONICS       3
HOME & KITCHEN    3
electronics       2
  Clothing        1
clothing          1
Name: count, dtype: int64

Unique categories: 8

In [12]:
# df.sample() shows random rows — less biased than head() which always shows the top
# Useful for spotting problems that only appear partway through the file
df.sample(5, random_state=42)   # random_state=42 makes it repeatable

,order_id,date,customer_name,product,category,quantity,unit_price,total,region,sales_rep
8,1008,2023-02-01,Henry Anderson,Wireless Headphones,electronics,2,150.00,300.0,South,Maria Lopez
16,1016,2023-03-07,Paul Garcia,Coffee Maker,HOME & KITCHEN,2,80.00,160.0,West,Sarah Williams
0,1001,2023-01-05,Alice Johnson,Laptop,Electronics,1,1200.00,1200.0,North,James Carter
24,1024,2023-03-30,David Brown,Cotton T-Shirt,Clothing,5,25.00,125.0,NaN,NaN
11,1011,2023-02-14,Karen Jackson,Standing Desk,Home & Kitchen,1,$350.00,NaN,North,James Carter

---

## 3.3 Selecting Columns and Filtering Rows

In [13]:
# Select one column — returns a Series
print(df['category'].head())

# Select multiple columns — returns a DataFrame
subset = df[['order_id', 'customer_name', 'product', 'total']]
subset.head()

0       Electronics
1        Clothing
2       ELECTRONICS
3    Home & Kitchen
4       Electronics
Name: category, dtype: str

   order_id   customer_name         product   total
0      1001   Alice Johnson          Laptop  1200.0
1      1002     Bob Smith    Cotton T-Shirt    75.0
2      1003  Carol Williams    Gaming Mouse    70.0
3      1004     David Brown    Coffee Maker    80.0
4      1005      Emma Jones          Laptop     NaN

In [6]:
# Filter rows: keep only Electronics
mask = df['category'].str.strip().str.upper() == 'ELECTRONICS'
electronics = df[mask]
print(f'Electronics rows: {len(electronics)}')
electronics[['order_id', 'product', 'category']].head()

Electronics rows: 10

   order_id              product     category
0      1001               Laptop  Electronics
2      1003         Gaming Mouse  ELECTRONICS
4      1005               Laptop  Electronics
5      1003         Gaming Mouse  ELECTRONICS
8      1008  Wireless Headphones  electronics

In [7]:
# .isin() filters by a list of values — cleaner than writing multiple == conditions
wanted_categories = ['Electronics', 'Clothing']
mask = df['category'].str.strip().str.title().isin(wanted_categories)
print(f'Rows in Electronics or Clothing: {mask.sum()}')
df[mask][['order_id', 'product', 'category']].head(8)

Rows in Electronics or Clothing: 18

   order_id              product      category
0      1001               Laptop   Electronics
1      1002       Cotton T-Shirt    Clothing
2      1003         Gaming Mouse   ELECTRONICS
4      1005               Laptop   Electronics
5      1003         Gaming Mouse   ELECTRONICS
6      1006       Slim-Fit Jeans      clothing
8      1008  Wireless Headphones   electronics
9      1009        Winter Jacket      Clothing

In [8]:
# Combine conditions with & (AND) — each condition MUST be in parentheses
high_value = df[
    (df['category'].str.strip().str.upper() == 'ELECTRONICS') &
    (pd.to_numeric(df['total'], errors='coerce') > 200)
]
print(f'High-value Electronics rows: {len(high_value)}')
high_value[['order_id', 'product', 'total']].head()

High-value Electronics rows: 4

    order_id              product   total
0       1001               Laptop  1200.0
8       1008  Wireless Headphones   300.0
10      1010      27-inch Monitor   400.0
17      1017               Laptop  1200.0

In [9]:
# .sort_values() sorts the result
# Useful after a filter to see the best or worst rows
top_orders = (
    df[['order_id', 'product', 'total']]
    .assign(total=pd.to_numeric(df['total'], errors='coerce'))
    .sort_values('total', ascending=False)
    .head(5)
)
print('Top 5 orders by total:')
print(top_orders)

Top 5 orders by total:
    order_id              product   total
0       1001               Laptop  1200.0
17      1017               Laptop  1200.0
10      1010      27-inch Monitor   400.0
23      1023        Standing Desk   350.0
8       1008  Wireless Headphones   300.0

---

## 3.4 Cleaning Data

Each step fixes one type of problem. Always work on a copy.

In [10]:
clean = df.copy()

# Step 1: Remove duplicates
before = len(clean)
clean = clean.drop_duplicates(subset=['order_id'])
print(f'Duplicates removed: {before - len(clean)}')

Duplicates removed: 1

In [11]:
# Step 2: Strip whitespace from text columns
clean['customer_name'] = clean['customer_name'].str.strip()
clean['product']       = clean['product'].str.strip()
print('Whitespace stripped.')

Whitespace stripped.

In [12]:
# Step 3: Standardise category — strip, title case
print('Before:', clean['category'].value_counts().to_dict())
clean['category'] = clean['category'].str.strip().str.title()
print('After:', clean['category'].value_counts().to_dict())

Before: {'Clothing': 6, 'Electronics': 5, 'Home & Kitchen': 5, 'HOME & KITCHEN': 3, 'ELECTRONICS': 2, 'electronics': 2, '  Clothing  ': 1, 'clothing': 1}
After: {'Electronics': 9, 'Clothing': 8, 'Home & Kitchen': 8}

In [13]:
# Step 4: Fix category typos using a dict passed to .replace()
# .replace() with a dict maps old values -> new values across the whole column
TYPO_MAP = {
    'Electrnics':    'Electronics',
    'Home & Kithen': 'Home & Kitchen',
}
clean['category'] = clean['category'].replace(TYPO_MAP)
print('After typo fix:', clean['category'].value_counts().to_dict())

After typo fix: {'Electronics': 9, 'Clothing': 8, 'Home & Kitchen': 8}

In [14]:
# Step 5: Clean unit_price — remove $, convert to float
clean['unit_price'] = (
    clean['unit_price']
    .astype(str)
    .str.replace('$', '', regex=False)
    .str.strip()
)
clean['unit_price'] = pd.to_numeric(clean['unit_price'], errors='coerce')
print(f'unit_price dtype: {clean["unit_price"].dtype}')
print(f'Null unit_prices: {clean["unit_price"].isnull().sum()}')

unit_price dtype: float64
Null unit_prices: 0

In [15]:
# Step 6: Convert quantity — Q3 data stores it as float (1.0, 2.0)
# Convert to numeric first, then to a nullable integer
clean['quantity'] = pd.to_numeric(clean['quantity'], errors='coerce')
print(f'quantity dtype before: {clean["quantity"].dtype}')
clean['quantity'] = clean['quantity'].astype('Int64')   # capital I = nullable integer
print(f'quantity dtype after:  {clean["quantity"].dtype}')
print(clean['quantity'].head(6))

quantity dtype before: int64
quantity dtype after:  Int64
0    1
1    3
2    2
3    1
4    1
6    2
Name: quantity, dtype: Int64

In [16]:
# Step 7: Fill missing totals
clean['total'] = pd.to_numeric(clean['total'], errors='coerce')
missing_before = clean['total'].isnull().sum()
clean['total'] = clean['total'].fillna(clean['quantity'] * clean['unit_price'])
print(f'Missing totals: {missing_before} before, {clean["total"].isnull().sum()} after')

Missing totals: 2 before, 0 after

In [17]:
# Step 8: Drop invalid rows
before = len(clean)
clean = clean[clean['quantity'] > 0]
print(f'Rows dropped (quantity <= 0): {before - len(clean)}')
print(f'Clean rows: {len(clean)}')

Rows dropped (quantity <= 0): 1
Clean rows: 24

---

## 3.5 Grouping and Summarising

Groupby works like SQL `GROUP BY`: split the data by a column, aggregate each group, combine the results.

In [18]:
# Total revenue and order count by category
revenue = (
    clean
    .groupby('category')['total']
    .agg(orders='count', revenue='sum')
    .sort_values('revenue', ascending=False)
    .round(2)
)
print(revenue)

                orders  revenue
category
Electronics          9   4735.0
Home & Kitchen       7   1505.0
Clothing             8    980.0

In [19]:
# Multiple aggregation functions: count, sum, mean, min, max
richer = (
    clean
    .groupby('category')['total']
    .agg(
        orders   = 'count',
        revenue  = 'sum',
        avg_order = 'mean',
        min_order = 'min',
        max_order = 'max'
    )
    .round(2)
    .sort_values('revenue', ascending=False)
)
print(richer)

                orders  revenue  avg_order  min_order  max_order
category
Electronics          9   4735.0     526.11       70.0     1200.0
Home & Kitchen       7   1505.0     215.00       65.0      350.0
Clothing             8    980.0     122.50       75.0      180.0

In [20]:
# Group by two columns: category AND sales_rep
by_cat_rep = (
    clean
    .groupby(['category', 'sales_rep'])
    .agg(
        orders  = ('order_id', 'count'),
        revenue = ('total', 'sum')
    )
    .round(2)
    .sort_values('revenue', ascending=False)
)
print(by_cat_rep.head(8))

                               orders  revenue
category       sales_rep
Electronics    James Carter         6   4290.0
Home & Kitchen David Chen           3    565.0
               Sarah Williams       2    510.0
Clothing       Sarah Williams       3    420.0
Electronics    Maria Lopez          2    375.0
Home & Kitchen James Carter         1    350.0
Clothing       David Chen           2    195.0
               Maria Lopez          1    150.0

In [21]:
# Sort the groupby result a different way
# Most orders first
by_orders = (
    clean
    .groupby('sales_rep')['order_id']
    .count()
    .rename('orders')
    .sort_values(ascending=False)
)
print('Sales reps by number of orders:')
print(by_orders)

Sales reps by number of orders:
sales_rep
James Carter      8
Sarah Williams    6
David Chen        5
Maria Lopez       4
Name: orders, dtype: int64

---

## 3.6 Writing to CSV

In [22]:
# Always use index=False so pandas does not write row numbers as a column
out_path = CLEAN / 'sales_q1_clean.csv'
clean.to_csv(out_path, index=False)
print(f'Saved {len(clean)} rows to {out_path}')

# Verify by reading back
check = pd.read_csv(out_path)
print(f'Re-read: {check.shape}')
check.head()

Saved 24 rows to ..\data\clean\sales_q1_clean.csv
Re-read: (24, 10)

,order_id,date,customer_name,product,category,quantity,unit_price,total,region,sales_rep
0,1001,2023-01-05,Alice Johnson,Laptop,Electronics,1,1200.0,1200.0,North,James Carter
1,1002,2023-01-08,Bob Smith,Cotton T-Shirt,Clothing,3,25.0,75.0,East,David Chen
2,1003,2023-01-12,Carol Williams,Gaming Mouse,Electronics,2,35.0,70.0,West,Sarah Williams
3,1004,15/01/2023,David Brown,Coffee Maker,Home & Kitchen,1,80.0,80.0,South,Maria Lopez
4,1005,2023-01-18,Emma Jones,Laptop,Electronics,1,1200.0,1200.0,North,James Carter

---

## Key Takeaways

1. `pd.read_csv()` loads a CSV into a DataFrame. Always check `.shape`, `.info()`, `.describe()`, `.isnull().sum()`, and `.value_counts()` before cleaning.
2. `df.sample(5)` shows random rows — less biased than `.head()` for spotting scattered problems.
3. Filter rows with a boolean mask. Use `.isin([list])` when matching against several values. Wrap every condition in parentheses when combining with `&` or `|`.
4. `.sort_values('column')` sorts results. Use `ascending=False` for largest first.
5. Always call `.copy()` before modifying a DataFrame so the original is preserved.
6. `.replace({old: new})` corrects typos across a whole column in one line.
7. `pd.to_numeric(series, errors='coerce')` converts to numbers and turns unparseable values into NaN. Use `astype('Int64')` (capital I) for a nullable integer column.
8. `.groupby().agg()` is the pandas equivalent of SQL `GROUP BY`. Pass a dict to `agg()` to compute count, sum, mean, min, and max all at once.
9. Always save with `index=False`.